### ISSUE TITLE
Improve All Books UI

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#8]
UI should be like Yakot app
UI should be sections which have (Free books, ....)
Each book in GridView should have Download Book or How to read it Buttons
Sort By most read and electronic book (most read and electronic book come first then most read and non electronic book)
change + in tabs to All Books

**Comment by EmanHylooz** [comment]
- The section to get from Eman (the genres)

**Comment by EmanHylooz** [comment]
![img_4997](https://cloud.githubusercontent.com/assets/6830380/22256512/ae38f482-e263-11e6-8edc-06b9bc960d68.PNG)

![img_4996](https://cloud.githubusercontent.com/assets/6830380/22256526/b63ff162-e263-11e6-8c55-620efcab877d.PNG)

![img_4998](https://cloud.githubusercontent.com/assets/6830380/22256537/bccef96a-e263-11e6-89a2-87afe814d3c5.PNG)

**Comment by EmanHylooz** [comment]
Below is the explanation of each of the above points: 
1. The page header has no title, please add the title الكتب into it
2. The same old bug, remove the white space from the beginning of the list (Check how it looks like in Yaqut App)
3. Use Abjjad Font for the Category Title (I will send you the font via Email) 
4. You forgot to add the button of تحميل الكتاب or كيف أقرؤه  underneath the book 
5. Add a link for المزيد> next to each category which will open another page that has all books vertically (same as our search results view, with the button for تحميل الكتاب)
6. Change the icon used into the same icon used in Yaqut as it is mre clear that this is الكتب 
7. Instead of having all the Categories listed with horizontal view of books, the rest of the categories can be that way and when clicking on them it will open the vertical view of the books. Below I will define which Categories to be on top with Horizontal view and which will be only listed.

**Comment by EmanHylooz** [comment]
7. The categories to be in the top with horizontal view of the books: 

1. كتب مجانيّة <--  sort those by the mostly downloaded first then the mostly read
2. ًكل الكتب المتوفرّة إلكترونيّا <--  sort those by the mostly downloaded first  then the mostly read
3.  كتب إلكترونية الأكثر قراءة<--- sort them by having first ebooks mostly read then the mostly read that  are not ebooks
4. كتب إلكترونية الأحدث إصداراً <-- sort them by having first ebooks mostly read then the mostly read that are not ebooks
5. أدب وروايات
6. سياسة
7. علم النفس

The rest of the categories only listing (Like Yaqut), where the user can click to see the list of the books in vertical view (kust like our search results view with تحميل الكتاب)
6. علوم إجتماعية
7. تاريخ وجغرافيا
8. فلسفة
9. بيوغرافيا ومذكرات
10. علوم إسلامية
11. إقتصاد وأعمال
12. المرأة والعائلة
13. أديان
14. عادات وتقاليد
15. كتب أطفال
16. سفر ورحلات
17. العلوم والطبيعة
18. لغة
19. فنون
20. صحافة وإعلام  
21. مراجع
22. رياضة وتسالي
23. قانون
24. طبخ وطعام
25. زراعة وحيوان 
26. كمبيوتر وإنترنت 
27. علوم عسكرية 
28. غرائب وأساطير 
29. صحة وطب

This is how the vertical view should look like (Same as the search results view) 
![img_5004](https://cloud.githubusercontent.com/assets/6830380/22258256/85758eec-e269-11e6-894f-45d88fd86675.PNG)

**Comment by Shimaa-Hassan** [comment]
tabs: ١- حسابي
٢- تنبيهات
٣- الكتب
٤- مكتبتي
٥- ابجديات

**Comment by EmanHylooz** [comment]
1. When I click on the اقرأ الكتاب the reader opens but the bottom of the app overrides the bottom of the book. 

2. The button تحميل الكتاب when clicked (knowing the user is subscribed), should become جاري التحميل  with loading indicator inside the button and then turns into اقرأ الكتاب (Just like its behavior everywhere else) Currently when you click تحميل الكتاب the button shrinks in size causing the design to corrupt, does not show جاري التحميل and it does not become اقرأ الكتاب unless I refreshed the page. The button should have the same size in all statuses (نحميل الكتاب، جاري التحميل، اقرأ الكتاب، كيف أقرؤه)

3. The button تحميل الكتاب and كيف أقرؤه has a different shape than how it looks like everywhere else (size, the corners, the color, the font)

![img_5042](https://cloud.githubusercontent.com/assets/6830380/23141061/99deca38-f7bd-11e6-89c2-ba5d8dd03639.PNG)

![img_5043](https://cloud.githubusercontent.com/assets/6830380/23141154/106b07de-f7be-11e6-9707-c0b67a96bc7f.PNG)

![img_5045](https://cloud.githubusercontent.com/assets/6830380/23141247/92f43c48-f7be-11e6-993c-c23821cb9be7.PNG)
